version: "3"

networks:
  web:
    external: true

services:
  sendsay:
    build: .
    restart: always
    labels:
      - traefik.backend=sendsay
      - traefik.frontend.rule=Host:sendsay.adorazel.online
      - traefik.docker.network=web
      - traefik.port=5000
    networks:
      - web